"""Autonomous pipeline: one command runs everything end to end and checks itself.

  python agent.py

Steps: build the database -> score -> compare with oldest-first -> hi 2 vs 3
-> ML check -> verify acceptance criteria -> write RESULTS.md and output/.
Exits with code 1 if any check fails, so it can run unattended (cron, CI).
"""
import sys
from datetime import datetime
from pathlib import Path

import db
import ml_check
from evaluation import compare
from scoring import Weights, TOP_N, rank, score_patients, to_rows

OUT = db.ROOT / "output"


def step(msg):
    print(f"[agent] {msg}")


def explain(m: dict, direction: str) -> str:
    reasons = ", ".join(m["why"]).lower()
    big = ("Low ejection fraction" in m["why"]) + ("High creatinine" in m["why"])
    if direction == "rose":
        core = ("has both a weak pump and struggling kidneys, so they gain the extra point twice"
                if big == 2 else "gained from the heavier weight")
    else:
        core = {0: "has neither big factor; all points came from smaller ones",
                1: "has only one of the two big factors, so patients with both overtook them",
                2: "was overtaken by patients with a higher total"}[big]
    return (f"P-{m['patient_id']} (age {m['age']}, EF {m['ef']}%, creatinine {m['creatinine']}) "
            f"went from rank {m['rank_before']} to {m['rank_after']}: {core}. Reasons: {reasons}.")


def run(csv: Path = db.CSV, db_path: Path | None = None, write: bool = True) -> dict:
    step("building database")
    report = db.build(csv, db_path, verbose=False)
    df = db.load(db_path)
    step(f"cleaning: {report['rows_dropped']} dropped, {report['rows_kept']} kept")

    w1, w2 = Weights(hi=2), Weights(hi=3)
    step("scoring and comparing strategies")
    cmp = compare(df, w1, w2)
    step("running ML check")
    ml = ml_check.run(df)

    checks = {
        "every patient scored": len(score_patients(df, w1)) == len(df),
        "top list has 25 rows (or all if fewer)": cmp["n"] == min(TOP_N, len(df)),
        "risk score beats oldest-first": cmp["deaths_v1"] > cmp["deaths_oldest_first"],
        "time and DEATH_EVENT not in output rows":
            all("time" not in r and "DEATH_EVENT" not in r
                for r in to_rows(rank(score_patients(df, w1)).head(TOP_N), w1)),
        "ML puts EF and creatinine on top": ml["top_two_are_ef_and_creatinine"],
        "rose/fell lists balance": len(cmp["rose"]) == len(cmp["fell"]),
    }
    for name, ok in checks.items():
        step(f"{'PASS' if ok else 'FAIL'}  {name}")

    result = {"report": report, "compare": cmp, "ml": ml, "checks": checks}
    if write:
        write_outputs(df, result, w1)
    return result


def write_outputs(df, r, w1):
    OUT.mkdir(exist_ok=True)
    rows = to_rows(rank(score_patients(df, w1)).head(TOP_N), w1)
    with open(OUT / "call_list.csv", "w") as f:
        f.write("rank,patient,age,ejection_fraction,creatinine,score,why\n")
        for x in rows:
            f.write(f'{x["rank"]},P-{x["patient_id"]},{x["age"]},{x["ef"]},{x["creatinine"]},'
                    f'{x["score"]},"{"; ".join(x["why"])}"\n')

    c, ml, rep = r["compare"], r["ml"], r["report"]
    lines = [
        "# Results",
        f"_Generated by agent.py on {datetime.now():%Y-%m-%d %H:%M}._",
        "",
        "## Data",
        f"- Patients in file: {rep['rows_in']}. Dropped: {rep['rows_dropped']}. Ranked: {rep['rows_kept']}.",
        f"- Deaths during follow-up (answer key only): {c['total_deaths']}.",
        "",
        "## Deaths caught in the top 25",
        "| Strategy | Deaths in top 25 | Mean EF | Mean creatinine | Mean age |",
        "|---|---|---|---|---|",
    ]
    for label, key in [("Oldest-first", "oldest_first"), ("Risk score, hi=2", "v1"),
                       ("Risk score, hi=3", "revised")]:
        s = c[key]
        lines.append(f"| {label} | {s['deaths']} | {s['mean_ef']}% | {s['mean_creatinine']} | {s['mean_age']} |")
    lines += [
        f"| ML probability (out-of-fold, for reference only) | {ml['deaths_top25']['ml_out_of_fold']} | | | |",
        "",
        f"- Overlap oldest-first vs risk score: {c['overlap_baseline_v1']}/25. "
        "The two lists pick almost completely different people.",
        f"- Overlap hi=2 vs hi=3: {c['overlap_v1_revised']}/25.",
        "",
        "## Who moved when the weak-heart weight went from 2 to 3",
    ]
    lines += [f"- Rose: {explain(m, 'rose')}" for m in c["rose"]]
    lines += [f"- Fell: {explain(m, 'fell')}" for m in c["fell"]]
    all_rose_both = all(m["pump_and_kidney"] for m in c["rose"])
    none_fell_both = not any(m["pump_and_kidney"] for m in c["fell"])
    lines += [
        "",
        f"Pattern check: every riser has both low EF and high creatinine: **{all_rose_both}**. "
        f"No faller has both: **{none_fell_both}**.",
        "",
        "## ML check (logistic regression, 6 inputs, `time` excluded)",
        f"- 5-fold cross-validated AUC: {ml['auc_cv_mean']} (folds {ml['auc_cv_folds']}).",
        "- Standardised coefficients, strongest first: " +
        ", ".join(f"{k} {v:+}" for k, v in ml["coefficients"].items()) + ".",
        f"- EF and creatinine are the two strongest factors: **{ml['top_two_are_ef_and_creatinine']}**.",
        f"- Whole-list AUC of the points score: hi=2 {ml['auc_points_hi2']}, hi=3 {ml['auc_points_hi3']}; "
        f"age alone {ml['auc_age_only']}.",
        f"- Learned weights on the same yes/no flags, rounded to points: {ml['learned_points']}.",
        "",
        "## Honest reading",
        "- The risk score beats oldest-first, but by a small margin in this top 25 "
        f"({c['deaths_v1']} vs {c['deaths_oldest_first']}). Across the whole list the gap is "
        f"clearer (AUC {ml['auc_points_hi2']} vs {ml['auc_age_only']}).",
        "- The ML check backs the main idea: pump and kidney numbers matter most. "
        "It also says age 70+ carries more weight than 1 point once EF and creatinine are "
        "turned into yes/no flags. Worth discussing, not hiding.",
        "- 299 patients, one retrospective study. Differences of 1-2 deaths could be chance.",
        "- This ranks who looks riskiest on paper. It does not diagnose anyone.",
        "",
        "## Self-checks",
    ]
    lines += [f"- {'PASS' if ok else 'FAIL'}: {name}" for name, ok in r["checks"].items()]
    (db.ROOT / "RESULTS.md").write_text("\n".join(lines) + "\n")
    step("wrote RESULTS.md and output/call_list.csv")


if __name__ == "__main__":
    res = run()
    sys.exit(0 if all(res["checks"].values()) else 1)
